---
title: "HW 05 - Legos"
author: "A U S"
date: "2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

 ## Load packages and data
  
  ```{r load-packages, message = FALSE}
install.packages("tidyverse")
install.packages("dplyr")
install.packages("remotes")
remotes::install_github("rstudio-education/dsbox")

library("tidyverse")
library("dplyr")
library("dsbox")
```
```{r}
load(file = "lego_sales.rda")
```

## Exercises

### Exercise 1
``` {r}
x <- sort(table(lego_sales$first_name))
tail(x,3)
```
jacob joseph jackson

### Exercise 2
``` {r}
x <- sort(table(lego_sales$theme))
tail(x,3)
```
Mixels, Nexo Knights, Star Wars

### Exercise 3
``` {r}
star <- subset(lego_sales, lego_sales$theme == 'Star Wars')
x <- sort(table(star$subtheme))
tail(x,1)
```

### Exercise 4
``` {r}
lego_sales <- lego_sales %>%
  mutate(age_group = case_when(.$age<=18 ~ "18 and under", (.$age>=19 & .$age<=25) ~ "19-25",(.$age >= 26 & .$age<=35) ~ "26-35",(.$age>=36 & .$age<=50) ~ "36-50", .$age>=51 ~"51 and over"))
```

### Exercise 5
``` {r}
x <- sort(table(lego_sales$age_group))
tail(x,1)
```
36-50 216

### Exercise 6
``` {r}
dfvalue=aggregate(lego_sales$us_price, by=list(Category=lego_sales$age_group), FUN=sum)
dfvalue[which.max(dfvalue$x),]
```
36-50 6641.84

### Exercise 7
``` {r}
dfvalue=aggregate(lego_sales$us_price, by=list(Category=lego_sales$theme), FUN=sum)
dfvalue[which.max(dfvalue$x),]
```
Star Wars 2842.25

### Exercise 8
``` {r}
lego_sales$area_code=substr(lego_sales$phone_number, start = 1, stop = 3)
dfvalue = aggregate(lego_sales$us_price, by=list(Category=lego_sales$area_code), FUN=sum)
dfvalue[which.max(dfvalue$x),]
```
973 444.94

### Exercise 9
#Question: Are products with more pieces more expensive?
#Answer: It seems yes, looking at a scatterplot between price and pieces.
``` {r}
sample_lego=lego_sales[lego_sales$pieces != 0, ]
plot(sample_lego$us_price, sample_lego$pieces, main="Scatterplot Example",xlab="pieces", ylab="price")
```

